# Generated by Django 3.0.5 on 2020-04-15 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('avAge', models.CharField(max_length=60)),
                ('avDailyIncomeInUSD', models.CharField(max_length=60)),
                ('avDailyIncomePopulation', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodType', models.CharField(max_length=60)),
                ('timeToElpase', models.CharField(max_length=60)),
                ('reportedCases', models.CharField(max_length=60)),
                ('Population', models.CharField(max_length=60)),
                ('totalHospitalBeds', models.CharField(max_length=60)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='convidapp.Region')),
            ],
        ),
    ]
